/**
 * Generates tool-specific AI context files from the single sources of truth:
 *   - AGENTS.md files (root and nested)
 *   - tools/ai/mcp-servers.json
 *
 * Usage:
 *   node tools/ai/sync.mts          write generated files
 *   node tools/ai/sync.mts --check  exit 1 when generated files are out of date
 *
 * Tests: tools/ai/sync.spec.mts (`npx nx test tools`).
 *
 * See docs/prd/starter.md, section 10.
 */
import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { dirname, join, posix, relative, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

interface McpServer {
  command: string;
  args: string[];
  /** Tools that get this server. Omitted means all tools. */
  tools?: AiTool[];
}

type AiTool = 'claude' | 'cursor' | 'vscode';

interface McpConfig {
  servers: Record<string, McpServer>;
}

const GENERATED_MARKER = 'Generated by `npm run ai:sync`';
const NX_BLOCK_START = '<!-- nx configuration start-->';
const NX_BLOCK_END = '<!-- nx configuration end-->';
const CORE_RULES_START = '<!-- core-rules:start -->';
const CORE_RULES_END = '<!-- core-rules:end -->';
const COPILOT_INSTRUCTIONS_DIR = '.github/instructions';
const IGNORED_DIRECTORIES = new Set([
  'node_modules',
  'dist',
  'coverage',
  'tmp',
  'out-tsc',
  '.git',
  '.nx',
  '.angular',
  '.claude',
  '.cursor',
  '.github',
  '.agents',
  'android',
  'ios',
]);

const toPosixPath = (path: string): string => path.split(sep).join(posix.sep);

const markdownHeader = (sourcePath: string): string =>
  `<!-- ${GENERATED_MARKER}. Do not edit: change ${sourcePath} instead. -->`;

function findFiles(root: string, fileName: string, directory = root): string[] {
  const entries = readdirSync(directory, { withFileTypes: true });

  return entries.flatMap((entry) => {
    const entryPath = join(directory, entry.name);

    if (entry.isDirectory()) {
      return IGNORED_DIRECTORIES.has(entry.name)
        ? []
        : findFiles(root, fileName, entryPath);
    }

    return entry.name === fileName
      ? [toPosixPath(relative(root, entryPath))]
      : [];
  });
}

function extractSection(
  content: string,
  startMarker: string,
  endMarker: string,
  sourcePath: string,
): string {
  const startIndex = content.indexOf(startMarker);
  const endIndex = content.indexOf(endMarker);

  if (startIndex === -1 || endIndex === -1 || endIndex < startIndex) {
    throw new Error(
      `${sourcePath}: missing section ${startMarker} … ${endMarker}`,
    );
  }

  return content.slice(startIndex, endIndex + endMarker.length);
}

function readText(root: string, path: string): string {
  return readFileSync(join(root, path), 'utf8');
}

function buildRootClaudeMd(rootAgentsMd: string): string {
  // Nx (`nx configure-ai-agents`) expects its block in CLAUDE.md, so it is mirrored here.
  const nxBlock = extractSection(
    rootAgentsMd,
    NX_BLOCK_START,
    NX_BLOCK_END,
    'AGENTS.md',
  );

  return `@AGENTS.md\n\n${nxBlock}\n`;
}

function buildNestedClaudeMd(agentsPath: string): string {
  return `${markdownHeader(agentsPath)}\n\n@AGENTS.md\n`;
}

function buildCopilotInstructions(rootAgentsMd: string): string {
  const coreRules = extractSection(
    rootAgentsMd,
    CORE_RULES_START,
    CORE_RULES_END,
    'AGENTS.md',
  )
    .replace(CORE_RULES_START, '')
    .replace(CORE_RULES_END, '')
    .trim();

  return [
    markdownHeader('the core-rules section of AGENTS.md'),
    '',
    '# Repository rules',
    '',
    'Full instructions: `AGENTS.md` in the repository root and in subdirectories.',
    '',
    coreRules,
    '',
  ].join('\n');
}

function buildCopilotPathInstructions(
  agentsPath: string,
  content: string,
): string {
  const directory = posix.dirname(agentsPath);

  return [
    '---',
    `applyTo: '${directory}/**'`,
    '---',
    '',
    markdownHeader(agentsPath),
    '',
    content.trim(),
    '',
  ].join('\n');
}

const copilotInstructionsFileName = (agentsPath: string): string =>
  `${posix.dirname(agentsPath).replaceAll('/', '-')}.instructions.md`;

function serversFor(config: McpConfig, tool: AiTool): [string, McpServer][] {
  return Object.entries(config.servers).filter(
    ([, server]) => server.tools?.includes(tool) ?? true,
  );
}

function buildMcpFiles(config: McpConfig): Map<string, string> {
  const toJson = (value: unknown): string =>
    `${JSON.stringify(value, null, 2)}\n`;
  const standardServers = (
    tool: AiTool,
  ): Record<string, Omit<McpServer, 'tools'>> =>
    Object.fromEntries(
      serversFor(config, tool).map(([name, { command, args }]) => [
        name,
        { command, args },
      ]),
    );
  const vscodeServers = Object.fromEntries(
    serversFor(config, 'vscode').map(([name, { command, args }]) => [
      name,
      { type: 'stdio', command, args },
    ]),
  );

  return new Map([
    ['.mcp.json', toJson({ mcpServers: standardServers('claude') })],
    ['.cursor/mcp.json', toJson({ mcpServers: standardServers('cursor') })],
    ['.vscode/mcp.json', toJson({ servers: vscodeServers })],
  ]);
}

/** Every generated file with the content it must have, derived from the sources in `root`. */
export function buildExpectedFiles(root: string): Map<string, string> {
  const rootAgentsMd = readText(root, 'AGENTS.md');
  const nestedAgentsPaths = findFiles(root, 'AGENTS.md').filter(
    (path) => path !== 'AGENTS.md',
  );
  const mcpConfig = JSON.parse(
    readText(root, 'tools/ai/mcp-servers.json'),
  ) as McpConfig;

  const expectedFiles = new Map<string, string>([
    ['CLAUDE.md', buildRootClaudeMd(rootAgentsMd)],
    ['.github/copilot-instructions.md', buildCopilotInstructions(rootAgentsMd)],
  ]);

  for (const agentsPath of nestedAgentsPaths) {
    const directory = posix.dirname(agentsPath);
    expectedFiles.set(
      `${directory}/CLAUDE.md`,
      buildNestedClaudeMd(agentsPath),
    );
    expectedFiles.set(
      `${COPILOT_INSTRUCTIONS_DIR}/${copilotInstructionsFileName(agentsPath)}`,
      buildCopilotPathInstructions(agentsPath, readText(root, agentsPath)),
    );
  }

  for (const [path, content] of buildMcpFiles(mcpConfig)) {
    expectedFiles.set(path, content);
  }

  return expectedFiles;
}

/** Generated files whose AGENTS.md source no longer exists. */
function findStaleFiles(
  root: string,
  expectedFiles: Map<string, string>,
): string[] {
  const directory = join(root, COPILOT_INSTRUCTIONS_DIR);
  const copilotFiles = existsSync(directory)
    ? readdirSync(directory).map(
        (fileName) => `${COPILOT_INSTRUCTIONS_DIR}/${fileName}`,
      )
    : [];
  const candidates = [...copilotFiles, ...findFiles(root, 'CLAUDE.md')];

  return candidates.filter(
    (path) =>
      !expectedFiles.has(path) &&
      readText(root, path).includes(GENERATED_MARKER),
  );
}

export interface SyncResult {
  readonly exitCode: number;
  /** Files written (sync) or out of date (check). */
  readonly changedFiles: readonly string[];
  /** Generated files without a source: removed (sync) or reported (check). */
  readonly staleFiles: readonly string[];
}

/** Writes the generated files in `root`, or with `check` only reports what differs. */
export function syncAiContext(
  root: string,
  { check = false }: { readonly check?: boolean } = {},
): SyncResult {
  const expectedFiles = buildExpectedFiles(root);
  const changedFiles = [...expectedFiles].filter(([path, content]) => {
    const absolutePath = join(root, path);
    return (
      !existsSync(absolutePath) ||
      readFileSync(absolutePath, 'utf8') !== content
    );
  });
  const staleFiles = findStaleFiles(root, expectedFiles);
  const result = {
    changedFiles: changedFiles.map(([path]) => path),
    staleFiles,
  };

  if (check) {
    return {
      ...result,
      exitCode: changedFiles.length === 0 && staleFiles.length === 0 ? 0 : 1,
    };
  }

  for (const [path, content] of changedFiles) {
    const absolutePath = join(root, path);
    mkdirSync(dirname(absolutePath), { recursive: true });
    writeFileSync(absolutePath, content);
  }

  for (const path of staleFiles) {
    rmSync(join(root, path));
  }

  return { ...result, exitCode: 0 };
}

function main(): void {
  const workspaceRoot = join(
    dirname(fileURLToPath(import.meta.url)),
    '..',
    '..',
  );
  const check = process.argv.includes('--check');
  const { exitCode, changedFiles, staleFiles } = syncAiContext(workspaceRoot, {
    check,
  });

  if (check && exitCode !== 0) {
    console.error(
      'ai:check: generated AI context files are out of date. Run `npm run ai:sync`.',
    );
    changedFiles.forEach((path) => console.error(`  outdated: ${path}`));
    staleFiles.forEach((path) => console.error(`  stale:    ${path}`));
  } else if (check) {
    console.log('ai:check: generated AI context files are up to date.');
  } else {
    changedFiles.forEach((path) => console.log(`ai:sync: wrote ${path}`));
    staleFiles.forEach((path) => console.log(`ai:sync: removed ${path}`));
    if (changedFiles.length === 0 && staleFiles.length === 0) {
      console.log('ai:sync: nothing to do.');
    }
  }

  process.exitCode = exitCode;
}

// Run only as a script (`node tools/ai/sync.mts`), not when imported by tests.
if (
  process.argv[1] &&
  resolve(process.argv[1]) === fileURLToPath(import.meta.url)
) {
  try {
    main();
  } catch (error: unknown) {
    console.error(
      `ai:sync: ${error instanceof Error ? error.message : String(error)}`,
    );
    process.exitCode = 1;
  }
}
