/**
 * Generates tool-specific AI context files from the single sources of truth:
 *   - AGENTS.md files (root and nested)
 *   - tools/ai/mcp-servers.json
 *
 * Usage:
 *   node tools/ai/sync.mts          write generated files
 *   node tools/ai/sync.mts --check  exit 1 when generated files are out of date
 *
 * See docs/prd/starter.md, section 10.
 */
import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { dirname, join, posix, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

interface McpServer {
  command: string;
  args: string[];
  /** Tools that get this server. Omitted means all tools. */
  tools?: AiTool[];
}

type AiTool = 'claude' | 'cursor' | 'vscode';

interface McpConfig {
  servers: Record<string, McpServer>;
}

const workspaceRoot = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const isCheckMode = process.argv.includes('--check');

const GENERATED_MARKER = 'Generated by `npm run ai:sync`';
const NX_BLOCK_START = '<!-- nx configuration start-->';
const NX_BLOCK_END = '<!-- nx configuration end-->';
const CORE_RULES_START = '<!-- core-rules:start -->';
const CORE_RULES_END = '<!-- core-rules:end -->';
const COPILOT_INSTRUCTIONS_DIR = '.github/instructions';
const IGNORED_DIRECTORIES = new Set([
  'node_modules',
  'dist',
  'coverage',
  'tmp',
  'out-tsc',
  '.git',
  '.nx',
  '.angular',
  '.claude',
  '.cursor',
  '.github',
  '.agents',
  'android',
  'ios',
]);

const toPosixPath = (path: string): string => path.split(sep).join(posix.sep);

const markdownHeader = (sourcePath: string): string =>
  `<!-- ${GENERATED_MARKER}. Do not edit: change ${sourcePath} instead. -->`;

function findFiles(fileName: string, directory = workspaceRoot): string[] {
  const entries = readdirSync(directory, { withFileTypes: true });

  return entries.flatMap((entry) => {
    const entryPath = join(directory, entry.name);

    if (entry.isDirectory()) {
      return IGNORED_DIRECTORIES.has(entry.name)
        ? []
        : findFiles(fileName, entryPath);
    }

    return entry.name === fileName
      ? [toPosixPath(relative(workspaceRoot, entryPath))]
      : [];
  });
}

function extractSection(
  content: string,
  startMarker: string,
  endMarker: string,
  sourcePath: string,
): string {
  const startIndex = content.indexOf(startMarker);
  const endIndex = content.indexOf(endMarker);

  if (startIndex === -1 || endIndex === -1 || endIndex < startIndex) {
    throw new Error(
      `${sourcePath}: missing section ${startMarker} … ${endMarker}`,
    );
  }

  return content.slice(startIndex, endIndex + endMarker.length);
}

function readText(path: string): string {
  return readFileSync(join(workspaceRoot, path), 'utf8');
}

function buildRootClaudeMd(rootAgentsMd: string): string {
  // Nx (`nx configure-ai-agents`) expects its block in CLAUDE.md, so it is mirrored here.
  const nxBlock = extractSection(
    rootAgentsMd,
    NX_BLOCK_START,
    NX_BLOCK_END,
    'AGENTS.md',
  );

  return `@AGENTS.md\n\n${nxBlock}\n`;
}

function buildNestedClaudeMd(agentsPath: string): string {
  return `${markdownHeader(agentsPath)}\n\n@AGENTS.md\n`;
}

function buildCopilotInstructions(rootAgentsMd: string): string {
  const coreRules = extractSection(
    rootAgentsMd,
    CORE_RULES_START,
    CORE_RULES_END,
    'AGENTS.md',
  )
    .replace(CORE_RULES_START, '')
    .replace(CORE_RULES_END, '')
    .trim();

  return [
    markdownHeader('the core-rules section of AGENTS.md'),
    '',
    '# Repository rules',
    '',
    'Full instructions: `AGENTS.md` in the repository root and in subdirectories.',
    '',
    coreRules,
    '',
  ].join('\n');
}

function buildCopilotPathInstructions(
  agentsPath: string,
  content: string,
): string {
  const directory = posix.dirname(agentsPath);

  return [
    '---',
    `applyTo: '${directory}/**'`,
    '---',
    '',
    markdownHeader(agentsPath),
    '',
    content.trim(),
    '',
  ].join('\n');
}

const copilotInstructionsFileName = (agentsPath: string): string =>
  `${posix.dirname(agentsPath).replaceAll('/', '-')}.instructions.md`;

function serversFor(config: McpConfig, tool: AiTool): [string, McpServer][] {
  return Object.entries(config.servers).filter(
    ([, server]) => server.tools?.includes(tool) ?? true,
  );
}

function buildMcpFiles(config: McpConfig): Map<string, string> {
  const toJson = (value: unknown): string =>
    `${JSON.stringify(value, null, 2)}\n`;
  const standardServers = (
    tool: AiTool,
  ): Record<string, Omit<McpServer, 'tools'>> =>
    Object.fromEntries(
      serversFor(config, tool).map(([name, { command, args }]) => [
        name,
        { command, args },
      ]),
    );
  const vscodeServers = Object.fromEntries(
    serversFor(config, 'vscode').map(([name, { command, args }]) => [
      name,
      { type: 'stdio', command, args },
    ]),
  );

  return new Map([
    ['.mcp.json', toJson({ mcpServers: standardServers('claude') })],
    ['.cursor/mcp.json', toJson({ mcpServers: standardServers('cursor') })],
    ['.vscode/mcp.json', toJson({ servers: vscodeServers })],
  ]);
}

function buildExpectedFiles(): Map<string, string> {
  const rootAgentsMd = readText('AGENTS.md');
  const nestedAgentsPaths = findFiles('AGENTS.md').filter(
    (path) => path !== 'AGENTS.md',
  );
  const mcpConfig = JSON.parse(
    readText('tools/ai/mcp-servers.json'),
  ) as McpConfig;

  const expectedFiles = new Map<string, string>([
    ['CLAUDE.md', buildRootClaudeMd(rootAgentsMd)],
    ['.github/copilot-instructions.md', buildCopilotInstructions(rootAgentsMd)],
  ]);

  for (const agentsPath of nestedAgentsPaths) {
    const directory = posix.dirname(agentsPath);
    expectedFiles.set(
      `${directory}/CLAUDE.md`,
      buildNestedClaudeMd(agentsPath),
    );
    expectedFiles.set(
      `${COPILOT_INSTRUCTIONS_DIR}/${copilotInstructionsFileName(agentsPath)}`,
      buildCopilotPathInstructions(agentsPath, readText(agentsPath)),
    );
  }

  for (const [path, content] of buildMcpFiles(mcpConfig)) {
    expectedFiles.set(path, content);
  }

  return expectedFiles;
}

/** Generated files whose AGENTS.md source no longer exists. */
function findStaleFiles(expectedFiles: Map<string, string>): string[] {
  const directory = join(workspaceRoot, COPILOT_INSTRUCTIONS_DIR);
  const copilotFiles = existsSync(directory)
    ? readdirSync(directory).map(
        (fileName) => `${COPILOT_INSTRUCTIONS_DIR}/${fileName}`,
      )
    : [];
  const candidates = [...copilotFiles, ...findFiles('CLAUDE.md')];

  return candidates.filter(
    (path) =>
      !expectedFiles.has(path) && readText(path).includes(GENERATED_MARKER),
  );
}

function run(): number {
  const expectedFiles = buildExpectedFiles();
  const changedFiles = [...expectedFiles].filter(([path, content]) => {
    const absolutePath = join(workspaceRoot, path);
    return (
      !existsSync(absolutePath) ||
      readFileSync(absolutePath, 'utf8') !== content
    );
  });
  const staleFiles = findStaleFiles(expectedFiles);

  if (isCheckMode) {
    if (changedFiles.length === 0 && staleFiles.length === 0) {
      console.log('ai:check: generated AI context files are up to date.');
      return 0;
    }

    console.error(
      'ai:check: generated AI context files are out of date. Run `npm run ai:sync`.',
    );
    changedFiles.forEach(([path]) => console.error(`  outdated: ${path}`));
    staleFiles.forEach((path) => console.error(`  stale:    ${path}`));
    return 1;
  }

  for (const [path, content] of changedFiles) {
    const absolutePath = join(workspaceRoot, path);
    mkdirSync(dirname(absolutePath), { recursive: true });
    writeFileSync(absolutePath, content);
    console.log(`ai:sync: wrote ${path}`);
  }

  for (const path of staleFiles) {
    rmSync(join(workspaceRoot, path));
    console.log(`ai:sync: removed ${path}`);
  }

  if (changedFiles.length === 0 && staleFiles.length === 0) {
    console.log('ai:sync: nothing to do.');
  }

  return 0;
}

try {
  process.exitCode = run();
} catch (error: unknown) {
  console.error(
    `ai:sync: ${error instanceof Error ? error.message : String(error)}`,
  );
  process.exitCode = 1;
}
